### PR TITLE
pbl: Extend call fastpath to constructor calls

### PR DESCRIPTION
**Pull request by jameysharp**
* Make constructor-call fastpath handle primitive returns

EnterJit overrides the frame's return value if it was a constructor call and the callee returned a primitive instead of an object. Do that in the return fastpath as well.

* Prevent JitScript from being discarded during CreateThis

* Use rooted reference to callee JSFunction

If CreateThis runs, there may be a GC pass, and the callee may move to a different address. In that case when CreateThis returns we need the GC to have updated the pointer we're using to the new location, so stash it in the rooted state.

### CODE REVIEW

**Comment by jameysharp** [comment]
CI failed for the jit-tests on a pbl-debug build, and I can locally confirm that the one test failing there fails for me too. It segfaults inside the `script.set(calleeScript);` during the call fastpath. Looking at `calleeScript`, at that moment it's pointing to an object full of `0x494949...`, so I think that memory was poisoned during a GC that probably happened during `CreateThis`. Therefore I'm guessing it needs to be `ReservedRooted` into `state` like `func` is, but I'm out of time to give that a shot today.

**Comment by cfallin** [comment]
This looks great, thanks! ACK on the test failure and likely fix; with that passing, happy to r+ and merge.

**Comment by jameysharp** [comment]
I believe I've fixed it. If nothing else fails in CI I think this is good to go.

**Review by cfallin — APPROVED** [review]
LGTM, thanks a bunch!

**Pull request merged**
