### PR TITLE
fastly js-compute-runtime patches on top of SM 123.0.1

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by cfallin** [comment]
Thanks a ton for doing this!

Overall question on structure: I see a bunch of commits still in the history here that have been upstreamed (e.g. the original PBL patch series) but are empty (e.g. [this one](https://github.com/bytecodealliance/gecko-dev/pull/41/commits/0bf7d9a58432992c33414ce41faeb6985f4aecaf)) or have small "leftover" changes, like a single blank line (e.g. [this one](https://github.com/bytecodealliance/gecko-dev/pull/41/commits/226f468c0a3482bd5579f060ff141de2a20433a2)). I suppose the process here was to rebase our entire branch with all commits, with changes that are now upstream "canceling out"?

It would personally be clearer to me at least if the commit history dropped commits altogether that we don't have to worry about anymore; would it be possible to e.g. ensure all the PBL patches that are upstream are completely out, and also sink/merge any changes to the existing patchset into the original commits rather than follow-ons? Basically I'm hoping we can optimize for "as few patches on top of an upstream commit-hash as possible" so it's clearer to future-us what our divergence is. I'm happy to dive in and help wrangle patches if you'd like a second pair of eyes on that :-)

**Comment by JakeChampion** [comment]
@cfallin This is ready for another review

I pulled all of the patches which landed in upstream after 123.0.1 and applied them to this branch - that made it much simpler for me to track which patches we have to carry ourselves and which we can eventually drop as we update to future releases from upstream.

All the patches (except 2) look to have landed in 125, so when that is released, we can upgrade and drop all pbl patches except for [774d321](https://github.com/bytecodealliance/gecko-dev/pull/41/commits/774d321670acba8fb226037ed8b4946e9bdc7881) and [12a9e73](https://github.com/bytecodealliance/gecko-dev/pull/41/commits/12a9e7301712539c400cd359c57aca808f6be29a) -- Note that I pulled out the deterministic trace into it's own patch, as that made it simpler for me to apply and keep track of which are patches we carry (previously it was within a patch which was partially implemented upstream)

**Review by cfallin — APPROVED** [review]
LGTM, thanks a ton for slogging through this rebase!

**Comment by JakeChampion** [comment]
@cfallin we only have squash merge enabled on this repo and I don't have the powers to change that -- should we squash merge this? 🤔

**Comment by cfallin** [comment]
Oh, definitely not, we want to preserve the commits in this case -- lemme see if I have the requisite powers...

**Pull request merged**
