### PR TITLE
AOT ICs: rebuild entire corpus.

### PR DESCRIPTION
**Pull request by cfallin**
In the course of the 124..127 upgrade, some IC bodies became invalid because of altered signatures of CacheIR opcodes. Nominally this should be fine in a system that never tries to execute such an invalid blob of bytecode. However, when we pre-weval all bodies in a weval build, we run into invalid memory reads in the weval phase just as we would if we tried to execute the IC at runtime in the IC interpreter: fundamentally, the corpus cannot have invalid bytecode in it. This PR thus removes the entire corpus and regenerates it:

- Remove `js/src/ics/IC-*`
- Build an engine with `--enable-aot-ics --enable-aot-ics-force --enable-aot-ics-enforce`
- Run jit-tests (`./mach jit-test`) and jstests (`./mach jstests`) with `AOT_ICS_KEEP_GOING=1`
- Use `js/src/ics/remove-duplicates.py` to remove duplicates among all the `IC-*` files in the gecko-dev root (jit-tests) and `js/src/tests` (jstests)
- Put all of these files into `js/src/ics`

Note for rebasing in the future: this should be squashed into the main AOT ICs commit.

### CODE REVIEW

**Comment by JakeChampion** [comment]
Will we need to remove and rebuild the corpus each time we update sm?

**Review by JakeChampion — APPROVED** [review]
I wonder if we can name the IC files based on their hash of their contents to avoid larger diffs and the need to have a deduplicate python script

**Comment by cfallin** [comment]
> Will we need to remove and rebuild the corpus each time we update sm?

Up until having the above realization about invalid bytecode, my answer was "I don't think so"; but now I'm having some Thoughts about the upgrade process. Unfortunately it's a fact of the checked-in string-of-macros format that it changes when arguments change; the only real way to ensure up-to-dateness would be to have some sort of typechecker/validator over all bodies in the corpus. This is sort of the second manifestation of problems from the add-or-remove-args-to-CacheIR-ops danger that I saw earlier in the rebase too (the first being that the interpreter itself gets out of sync in its bytecode parsing). So I think the answer is: I need to come up with more type safety here, and the hopeful answer is eventually no, but for now we need to be pretty careful.

**Comment by cfallin** [comment]
Separately, I'm just now publishing a version of weval that is resilient to failures during partial eval -- if we try to partial eval bad bytecode, we should just skip that function specialization, not error out entirely. That'll make us resilient to "useless corpus" at least.

**Pull request merged**
